### ISSUE TITLE
CREATE DATABASE 'test1.fdb' page_size 16384  DEFAULT CHARACTER SET UTF8 error by jdbc

### ISSUE THREAD

**Issue by yuedaxia76** [FirebirdSQL/jaybird#27]
when execute "CREATE DATABASE 'test1.fdb' page_size 16384  DEFAULT CHARACTER SET UTF8" error:
java.sql.SQLSyntaxErrorException: Dynamic SQL Error; SQL error code = -530; Cannot prepare a CREATE DATABASE/SCHEMA statement [SQLState:42000, ISC error code:335544597]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:529)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:304)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:138)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:202)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readSingleResponse(AbstractWireOperations.java:169)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:153)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readGenericResponse(AbstractWireOperations.java:255)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readGenericResponse(AbstractFbWireDatabase.java:173)
	at org.firebirdsql.gds.ng.wire.version11.V11Statement.prepare(V11Statement.java:89)
	at org.firebirdsql.jdbc.FBStatement.prepareFixedStatement(FBStatement.java:847)
	at org.firebirdsql.jdbc.FBStatement.internalExecute(FBStatement.java:833)
	at org.firebirdsql.jdbc.FBStatement.executeImpl(FBStatement.java:461)
	at org.firebirdsql.jdbc.FBStatement.execute(FBStatement.java:447)
	at com.gentlesoft.commons.util.database.util.SQLProcessor.createDb(SQLProcessor.java:2709)
	at com.gentlesoft.gdao.test.TestCreDb.testCreDb(TestCreDb.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by yuedaxia76** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gentlesoft.gdao.test;

import com.gentlesoft.commons.util.UtilValidate;
 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

/**
 *
 * @author lenovo
 */
public class TestCreDb {

    private static final Logger log = LoggerFactory.getLogger(TestCreDb.class);
    protected Connection conn;
 

    @BeforeTest
    public void initest() throws  Exception {
        Class.forName("org.firebirdsql.jdbc.FBDriver").newInstance();
        conn = DriverManager.getConnection("jdbc:firebirdsql://localhost:3050/C:/Program Files/Firebird/Firebird_4_0/DEV.FDB?encoding=UTF8", "SYSDBA", "masterkey");
 

    }

    @Test
    public void testCreDb() throws SQLException, Exception {
 
 
             String creSql = "CREATE DATABASE 'test1.fdb' page_size 16384  DEFAULT CHARACTER SET UTF8";
        
        
        try (Statement st = getConnection().createStatement();) {
 

 
            st.execute(creSql);
 
        }
    }

 

    @AfterTest
    public void clear() throws SQLException {
        log.info("clear test data");

        if (conn != null) {
            conn.close();
        }
    }
}

**Comment by yuedaxia76** [comment]
jdbc 4.0.0-beta-1
firebird 4.0 bata

**Comment by yuedaxia76** [comment]
jdbc 4.0.0-beta-1
firebird 4.0 beta 1

**Comment by mrotteveel** [comment]
Did this work on earlier Firebird version or earlier Jaybird versions?

**Comment by yuedaxia76** [comment]
jaybird 3.07 ,firebird 4.0 beta 1 
java.sql.SQLSyntaxErrorException: Dynamic SQL Error; SQL error code = -530; Cannot prepare a CREATE DATABASE/SCHEMA statement [SQLState:42000, ISC error code:335544597]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:527)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:302)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:138)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:202)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readSingleResponse(AbstractWireOperations.java:169)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:153)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readGenericResponse(AbstractWireOperations.java:255)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readGenericResponse(AbstractFbWireDatabase.java:173)
	at org.firebirdsql.gds.ng.wire.version11.V11Statement.prepare(V11Statement.java:89)
	at org.firebirdsql.jdbc.FBStatement.prepareFixedStatement(FBStatement.java:1370)
	at org.firebirdsql.jdbc.FBStatement.internalExecute(FBStatement.java:1356)
	at org.firebirdsql.jdbc.FBStatement.executeImpl(FBStatement.java:840)
	at org.firebirdsql.jdbc.FBStatement.execute(FBStatement.java:826)
	at com.gentlesoft.commons.util.database.util.SQLProcessor.createDb(SQLProcessor.java:2711)
	at com.gentlesoft.gdao.test.TestCreDb.testCreDb(TestCreDb.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: Dynamic SQL Error

**Comment by yuedaxia76** [comment]
Statement boolean execute(String sql) should not be executed with Prepared Statement

**Comment by mrotteveel** [comment]
> Statement boolean execute(String sql) should not be executed with Prepared Statement

It isn't executed with a `java.sql.PreparedStatement`, however Jaybird needs to prepare statements executed with `java.sql.Statement`, otherwise it can't know what type it is and what columns - if any - it returns.

Unfortunately, in this case you're also hitting a specific Firebird implementation restriction for `CREATE DATABASE`. For example, executing the same statement in FlameRobin will yield the same error. Using the low-level API with an existing connection to use 'execute immediate' will also not work (it will just do nothing), because creating a database while attached to an existing database doesn't work either (although I'm not sure if that is a Jaybird limitation or a Firebird limitation).

The solution is to use `FBManager` to create the database

    FBManager fbManager = new FBManager();
    fbManager.setServer("localhost");
    fbManager.setUserName("sysdba");
    fbManager.setPassword("masterkey");
    fbManager.setFileName("test1.fdb");
    fbManager.setDefaultCharacterSet("UTF8");
    fbManager.setPageSize(PageSizeConstants.SIZE_16K);
    fbManager.setCreateOnStart(true);
    fbManager.start();

In theory, it should be possible to create a database in the low-level API with a connected, but not attached connection, but at the moment this only works with native connections, and for some reason fails with the pure java implementation:

    IConnectionProperties props = new FbConnectionProperties();
    props.setServerName("localhost");
    props.setPortNumber(3050);
    props.setDatabaseName("D:/data/db/testdatabase.fdb");
    props.setUser("sysdba");
    props.setPassword("masterkey");
    props.setEncoding("UTF8");
    FbDatabaseFactory databaseFactory = GDSFactory.getDatabaseFactoryForType(GDSType.getType("NATIVE"));
    try (FbDatabase fbDatabase = databaseFactory.connect(props)) {
        fbDatabase.executeImmediate(
                "CREATE DATABASE 'D:/temp/test1.fdb' user 'sysdba' password 'masterkey' page_size 16384 DEFAULT CHARACTER SET UTF8", null);
    }

Note that including the username and password in the `CREATE DATABASE` statement is required.

Although I understand that it would be handy to be able to execute `CREATE DATABASE` this way, right now it is simply not possible in Jaybird. As far as I can tell, it has never been possible in the 18 year history of Jaybird. I have created http://tracker.firebirdsql.org/browse/JDBC-598 for this, but as I'm not sure if it is even possible to do this and as I don't consider it a high priority, I can't say when (or even if) it will get fixed.

As an alternative, as you're doing this in a unit test, you could consider using https://github.com/FirebirdSQL/firebird-testcontainers-java

I will close this issue, so http://tracker.firebirdsql.org/browse/JDBC-598 will be the single issue to track this.
