### ISSUE TITLE
DriverExample  : Failed to initialize Jaybird native library

### ISSUE THREAD

**Issue by broodingimu** [FirebirdSQL/jaybird#35]
DriverExample {
    private static final String URL_DEFAULT = "jdbc:firebirdsql:embedded:C:\\Users\\qiuba\\Desktop\\SHOPDATA_62424.FDB";

Exception in thread "main" java.lang.RuntimeException: Failed to initialize Jaybird native library. This is most likely due to a failure to load the firebird client library.
	at org.firebirdsql.gds.impl.jni.JniGDSImpl.attemptToLoadAClientLibraryFromList(JniGDSImpl.java:106)
	at org.firebirdsql.gds.impl.jni.EmbeddedGDSImpl.<init>(EmbeddedGDSImpl.java:31)
	at org.firebirdsql.gds.impl.jni.EmbeddedGDSImpl.<init>(EmbeddedGDSImpl.java:21)
	at org.firebirdsql.gds.impl.jni.EmbeddedGDSFactoryPlugin.getGDS(EmbeddedGDSFactoryPlugin.java:40)
	at org.firebirdsql.gds.impl.GDSFactory.getGDSForType(GDSFactory.java:262)
	at org.firebirdsql.jca.FBManagedConnectionFactory.getGDS(FBManagedConnectionFactory.java:123)
	at org.firebirdsql.jdbc.AbstractDriver.connect(AbstractDriver.java:130)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.test.DriverExample.main(DriverExample.java:202)

**Comment by mrotteveel** [comment]
The error indicates you don't have the Jaybird native library (jaybird22.dll/libjaybird22.dll) on the java library path, or possibly the Firebird native client (fbclient.dll/libfbclient.so). The stacktrace also indicates you're using Jaybird 2.2 or earlier. See also [Using Type 2 and Embedded Server driver](https://www.firebirdsql.org/file/documentation/drivers_documentation/java/2.2.x/release_notes.html#using-type-2-and-embedded-server-driver) in the Jaybird 2.2 release notes.

For further support questions, please post to https://groups.google.com/g/firebird-java.

**Comment by broodingimu** [comment]
Firebird JCA-JDBC driver version 3.0 registered with driver manager.
WARNING: No connection character set specified (property lc_ctype, encoding, charSet or localEncoding), defaulting to character set NONE
java.sql.SQLException: unsupported on-disk structure for file C:\USERS\QIUBA\DESKTOP\SHOPDATA_62424.FDB; found 11.2, support 11.1 [SQLState:HY000, ISC error code:335544379]
Unable to establish a connection through the driver manager.	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:532)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:302)
	at org.firebirdsql.gds.ng.jna.JnaConnection.processStatusVector(JnaConnection.java:146)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.processStatusVector(JnaDatabase.java:483)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.processStatusVector(JnaDatabase.java:475)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.attachOrCreate(JnaDatabase.java:131)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.attach(JnaDatabase.java:108)
	at org.firebirdsql.jca.FBManagedConnection.<init>(FBManagedConnection.java:145)
	at org.firebirdsql.jca.FBManagedConnectionFactory.createManagedConnection(FBManagedConnectionFactory.java:558)
	at org.firebirdsql.jca.FBStandAloneConnectionManager.allocateConnection(FBStandAloneConnectionManager.java:65)
	at org.firebirdsql.jdbc.FBDataSource.getConnection(FBDataSource.java:124)
	at org.firebirdsql.jdbc.FBDriver.connect(FBDriver.java:143)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.test.DriverExample.main(DriverExample.java:202)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: unsupported on-disk structure for file C:\USERS\QIUBA\DESKTOP\SHOPDATA_62424.FDB; found 11.2, support 11.1
