### ISSUE TITLE
found 11.2, support 11.1 [SQLState:HY000, ISC error code:335544379]

### ISSUE THREAD

**Issue by broodingimu** [FirebirdSQL/jaybird#36]
Firebird JCA-JDBC driver version 3.0 registered with driver manager.
21 2020 12:41:15 上午 org.firebirdsql.logging.JulLogger warn
 WARNING: No connection character set specified (property lc_ctype, encoding, charSet or localEncoding), defaulting to character set NONE
java.sql.SQLException: unsupported on-disk structure for file C:\USERS\QIUBA\DESKTOP\SHOPDATA_62424.FDB; found 11.2, support 11.1 [SQLState:HY000, ISC error code:335544379]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:532)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:302)
	at org.firebirdsql.gds.ng.jna.JnaConnection.processStatusVector(JnaConnection.java:146)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.processStatusVector(JnaDatabase.java:483)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.processStatusVector(JnaDatabase.java:475)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.attachOrCreate(JnaDatabase.java:131)
	at org.firebirdsql.gds.ng.jna.JnaDatabase.attach(JnaDatabase.java:108)
	at org.firebirdsql.jca.FBManagedConnection.<init>(FBManagedConnection.java:145)
	at org.firebirdsql.jca.FBManagedConnectionFactory.createManagedConnection(FBManagedConnectionFactory.java:558)
	at org.firebirdsql.jca.FBStandAloneConnectionManager.allocateConnection(FBStandAloneConnectionManager.java:65)
	at org.firebirdsql.jdbc.FBDataSource.getConnection(FBDataSource.java:124)
	at org.firebirdsql.jdbc.FBDriver.connect(FBDriver.java:143)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.test.DriverExample.main(DriverExample.java:202)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: unsupported on-disk structure for file C:\USERS\QIUBA\DESKTOP\SHOPDATA_62424.FDB; found 11.2, support 11.1
Unable to establish a connection through the driver manager.
unsupported on-disk structure for file C:\USERS\QIUBA\DESKTOP\SHOPDATA_62424.FDB; found 11.2, support 11.1 [SQLState:HY000, ISC error code:335544379]
Error Code: 335544379
SQL State: HY000
Closing database resources and rolling back any changes we made to the database.

**Comment by mrotteveel** [comment]
As I mentioned on the previous issue you created, support questions shouldn't be posted here. Questions about Jaybird should to to https://groups.google.com/g/firebird-java.

However, this is a Firebird support question, not a problem with Jaybird. Please direct your question to https://groups.google.com/g/firebird-support, or see [Why do I get an unsupported on-disk structure error when opening a Firebird database?](https://stackoverflow.com/questions/43643098/why-do-i-get-an-unsupported-on-disk-structure-error-when-opening-a-firebird-data)
