### ISSUE TITLE
NativeResourceUnloadWebListener fails when JNA is not on the class path.

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/jaybird#686]
The NativeResourceUnloadWebListener fails when JNA is not on the classpath as reported on https://groups.google.com/g/firebird-java/c/aRrtXQGR5Dg, as it will fail to find `com.sun.jna.Library` when loading `FbClientLibrary`. The lookup of the class loader should be isolated, or any errors when loading it should be swallowed.

```none
Exception sending context initialized event to listener instance of class [org.firebirdsql.gds.ng.jna.NativeResourceUnloadWebListener]
java.lang.NoClassDefFoundError: com/sun/jna/Library
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2478)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:870)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1371)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
        at org.firebirdsql.gds.ng.jna.NativeResourceUnloadWebListener.jaybirdLoadedInContext(NativeResourceUnloadWebListener.java:54)
        at org.firebirdsql.gds.ng.jna.NativeResourceUnloadWebListener.contextInitialized(NativeResourceUnloadWebListener.java:40)
```

Workarounds:
* Set system property `org.firebirdsql.nativeResourceShutdownDisable` to true
* Add jna-5.5.0 (or higher) to the class path

**Comment by mrotteveel** [comment]
Fixed by checking class loader of FbClientDatabaseFactory instead.
