### ISSUE TITLE
Android connect  \{(\d+)} 

### ISSUE THREAD

**Issue by ApiDjango** [FirebirdSQL/jaybird#736]
Gradle  implementation 'org.firebirdsql.jdbc:jaybird:5.0.1.java11'

 java.lang.ExceptionInInitializerError
        at org.firebirdsql.gds.GDSExceptionHelper.getSQLState(GDSExceptionHelper.java:104)
        at org.firebirdsql.gds.ng.FbExceptionBuilder$ExceptionInformation.<init>(FbExceptionBuilder.java:510)
        at org.firebirdsql.gds.ng.FbExceptionBuilder.setNextExceptionInformation(FbExceptionBuilder.java:451)
        at org.firebirdsql.gds.ng.FbExceptionBuilder.nonTransientConnectionException(FbExceptionBuilder.java:146)
        at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:267)
        at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.performConnect(FbWireDatabaseFactory.java:50)
        at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:39)
        at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:32)
        at org.firebirdsql.jaybird.xca.FBManagedConnection.<init>(FBManagedConnection.java:120)
        at org.firebirdsql.jaybird.xca.FBManagedConnectionFactory.createManagedConnection(FBManagedConnectionFactory.java:375)
        at org.firebirdsql.jaybird.xca.FBStandAloneConnectionManager.allocateConnection(FBStandAloneConnectionManager.java:48)
        at org.firebirdsql.jdbc.FBDataSource.getConnection(FBDataSource.java:72)
        at org.firebirdsql.jdbc.FBDriver.connect(FBDriver.java:137)
        at java.sql.DriverManager.getConnection(DriverManager.java:580)
        at java.sql.DriverManager.getConnection(DriverManager.java:218)
        at com.nsk.kassa.AuthorizationActivity$FirebirdConnection.getConnection(AuthorizationActivity.java:42)
        at com.nsk.kassa.AuthorizationActivity$1.onClick(AuthorizationActivity.java:62)
        at android.view.View.performClick(View.java:7441)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 8
    \{(\d+)}
            ^

**Comment by mrotteveel** [comment]
Jaybird does not work on Android as it uses Java features (like in the case certain regex features) which are not available on Android, which are available in normal Java. 

See also [Can Jaybird be used on Android](https://www.firebirdsql.org/file/documentation/drivers_documentation/java/faq.html#_can_jaybird_be_used_on_android)
